In [1]:
#import Pandas and Numpy
import pandas as pd
import numpy as np

In [2]:
#import data
df = pd.read_csv(r"C:\Users\Johanna\Desktop\NexAfrica Internship\Sample - Superstore.csv", encoding="cp1252")

In [7]:
#view the first 5 rows
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
#view the last 5 rows
df.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [8]:
#check the size of the data
df.shape

(9994, 21)

In [10]:
#view column names
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [11]:
#view colun names
for column in df.columns:
    print(column)

Row ID
Order ID
Order Date
Ship Date
Ship Mode
Customer ID
Customer Name
Segment
Country
City
State
Postal Code
Region
Product ID
Category
Sub-Category
Product Name
Sales
Quantity
Discount
Profit

In [12]:
#view data types
df.dtypes

Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code        int64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [14]:
#check general information about dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row_ID         9994 non-null   int64
 1   Order_ID       9994 non-null   str
 2   Order_Date     9994 non-null   str
 3   Ship_Date      9994 non-null   str
 4   Ship_Mode      9994 non-null   str
 5   Customer_ID    9994 non-null   str
 6   Customer_Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal_Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product_ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub_Category   9994 non-null   str
 16  Product_Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), str(15)
memory usage: 3.3 MB

In [15]:
#Clean column names
df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("-", "_")
)

In [16]:
#remove unnecesary space
text_columns = df.select_dtypes(include="string").columns

for column in text_columns:
    df[column] = df[column].str.strip()

In [17]:
#convert the date formats
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"], errors="coerce")

In [18]:
#view data
df[["Order_Date", "Ship_Date"]].head()

  Order_Date  Ship_Date
0 2016-11-08 2016-11-11
1 2016-11-08 2016-11-11
2 2016-06-12 2016-06-16
3 2015-10-11 2015-10-18
4 2015-10-11 2015-10-18

In [19]:
#convert numeric columns
numeric_columns = [
    "Row_ID",
    "Postal_Code",
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(df[column], errors="coerce")

In [20]:
#check for missing values
df.isnull().sum()

Row_ID           0
Order_ID         0
Order_Date       0
Ship_Date        0
Ship_Mode        0
Customer_ID      0
Customer_Name    0
Segment          0
Country          0
City             0
State            0
Postal_Code      0
Region           0
Product_ID       0
Category         0
Sub_Category     0
Product_Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [21]:
#calculate total
df.isnull().sum().sum()

np.int64(0)

In [22]:
#check for duplicates
df.duplicated().sum()

np.int64(0)

In [23]:
#remove duplicates
df = df.drop_duplicates()

In [24]:
#check invalid quantities
df[df["Quantity"] <= 0]

Empty DataFrame
Columns: [Row_ID, Order_ID, Order_Date, Ship_Date, Ship_Mode, Customer_ID, Customer_Name, Segment, Country, City, State, Postal_Code, Region, Product_ID, Category, Sub_Category, Product_Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [25]:
#check invalid quantities
df = df[df["Quantity"] > 0]

In [26]:
#check invalid discounts
df[(df["Discount"] < 0) | (df["Discount"] > 1)]

Empty DataFrame
Columns: [Row_ID, Order_ID, Order_Date, Ship_Date, Ship_Mode, Customer_ID, Customer_Name, Segment, Country, City, State, Postal_Code, Region, Product_ID, Category, Sub_Category, Product_Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [27]:
#check invalid discounts
df["Discount"] = df["Discount"].clip(0, 1)

In [28]:
#calculate shipping days
df["Shipping_Days"] = (
    df["Ship_Date"] - df["Order_Date"]
).dt.days

In [35]:
df[["Order_Date", "Ship_Date", "Shipping_Days"]].head()

  Order_Date  Ship_Date  Shipping_Days
0 2016-11-08 2016-11-11              3
1 2016-11-08 2016-11-11              3
2 2016-06-12 2016-06-16              4
3 2015-10-11 2015-10-18              7
4 2015-10-11 2015-10-18              7

In [29]:
#create order year
df["Order_Year"] = df["Order_Date"].dt.year

In [30]:
#create order month
df["Order_Month"] = df["Order_Date"].dt.month

In [33]:
#create order month
df["Order_Month_Name"] = df["Order_Date"].dt.strftime("%B")

In [34]:
#create order quarter
df["Order_Quarter"] = "Q" + df["Order_Date"].dt.quarter.astype(str)

In [32]:
#calculate order sales
df["Gross_Sales"] = np.where(
    df["Discount"] < 1,
    df["Sales"] / (1 - df["Discount"]),
    np.nan
)

In [35]:
#calculate discount amount
df["Discount_Amount"] = (
    df["Gross_Sales"] - df["Sales"]
)

In [36]:
#calculate sale per unit
df["Sales_Per_Unit"] = (
    df["Sales"] / df["Quantity"]
)

In [37]:
#calculate profit margin
df["Profit_Margin"] = np.where(
    df["Sales"] != 0,
    df["Profit"] / df["Sales"],
    np.nan
)

In [38]:
#view profit percentage
df["Profit_Margin"] = df["Profit_Margin"] * 100

In [40]:
#create profit status
df["Profit_Status"] = np.where(
    df["Profit"] >= 0,
    "Profitable",
    "Loss"
)

In [41]:
#rounf calculated values
df["Gross_Sales"] = df["Gross_Sales"].round(2)

df["Discount_Amount"] = df["Discount_Amount"].round(2)

df["Sales_Per_Unit"] = df["Sales_Per_Unit"].round(2)

df["Profit_Margin"] = df["Profit_Margin"].round(2)

In [42]:
#view first 5 rows
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Shipping_Days,Order_Year,Order_Month,Order_Quarter,Gross_Sales,Order_Month_Name,Discount_Amount,Sales_Per_Unit,Profit_Margin,Profit_Status
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,2016,11,Q4,261.96,November,0.00,130.98,16.00,Profitable
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,3,2016,11,Q4,731.94,November,0.00,243.98,30.00,Profitable
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,4,2016,6,Q2,14.62,June,0.00,7.31,47.00,Profitable
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,7,2015,10,Q4,1741.05,October,783.47,191.52,-40.00,Loss
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,7,2015,10,Q4,27.96,October,5.59,11.18,11.25,Profitable

In [45]:
#view cleaned rows and columns
df.shape

(9994, 31)

In [44]:
#save cleaned dataset
df.to_csv(
    "Superstore_Cleaned.csv",
    index=False
)

In [46]:
#create data dictionary
data_dictionary = pd.DataFrame({
    "Field": df.columns,
    "Data_Type": [df[column].dtype for column in df.columns],
    "Description": [
        "Description of " + column
        for column in df.columns
    ]
})

In [51]:
data_dictionary

               Field       Data_Type                      Description
0             Row_ID           int64            Description of Row_ID
1           Order_ID             str          Description of Order_ID
2         Order_Date  datetime64[us]        Description of Order_Date
3          Ship_Date  datetime64[us]         Description of Ship_Date
4          Ship_Mode             str         Description of Ship_Mode
5        Customer_ID             str       Description of Customer_ID
6      Customer_Name             str     Description of Customer_Name
7            Segment             str           Description of Segment
8            Country             str           Description of Country
9               City             str              Description of City
10             State             str             Description of State
11       Postal_Code           int64       Description of Postal_Code
12            Region             str            Description of Region
13        Product_ID             str        Description of Product_ID
14          Category             str          Description of Category
15      Sub_Category             str      Description of Sub_Category
16      Product_Name             str      Description of Product_Name
17             Sales         float64             Description of Sales
18          Quantity           int64          Description of Quantity
19          Discount         float64          Description of Discount
20            Profit         float64            Description of Profit
21     Shipping_Days           int64     Description of Shipping_Days
22        Order_Year           int32        Description of Order_Year
23       Order_Month           int32       Description of Order_Month
24  Order_Month_Name             str  Description of Order_Month_Name
25     Order_Quarter             str     Description of Order_Quarter
26       Gross_Sales         float64       Description of Gross_Sales
27   Discount_Amount         float64   Description of Discount_Amount
28    Sales_Per_Unit         float64    Description of Sales_Per_Unit
29     Profit_Margin         float64     Description of Profit_Margin
30     Profit_Status             str     Description of Profit_Status

In [47]:
#replace generic descriptions
data_dictionary = pd.DataFrame([
    ["Order_ID", "string", "Unique identification number for the order"],
    ["Order_Date", "datetime", "Date when the order was placed"],
    ["Ship_Date", "datetime", "Date when the order was shipped"],
    ["Customer_ID", "string", "Unique identification number for the customer"],
    ["Category", "string", "Main product category"],
    ["Sub_Category", "string", "Product sub-category"],
    ["Sales", "float", "Sales value after discount"],
    ["Quantity", "int", "Number of units sold"],
    ["Discount", "float", "Discount applied to the order"],
    ["Profit", "float", "Profit generated from the order"],
    ["Shipping_Days", "int", "Number of days between order and shipment"],
    ["Gross_Sales", "float", "Estimated sales before discount"],
    ["Discount_Amount", "float", "Estimated monetary value of the discount"],
    ["Sales_Per_Unit", "float", "Sales divided by quantity"],
    ["Profit_Margin", "float", "Profit as a percentage of sales"],
    ["Profit_Status", "string", "Shows whether the transaction generated profit or loss"]
], columns=["Field", "Data_Type", "Description"])

data_dictionary

,Field,Data_Type,Description
0,Order_ID,string,Unique identification number for the order
1,Order_Date,datetime,Date when the order was placed
2,Ship_Date,datetime,Date when the order was shipped
3,Customer_ID,string,Unique identification number for the customer
4,Category,string,Main product category
5,Sub_Category,string,Product sub-category
6,Sales,float,Sales value after discount
7,Quantity,int,Number of units sold
8,Discount,float,Discount applied to the order
9,Profit,float,Profit generated from the order
10,Shipping_Days,int,Number of days between order and shipment
11,Gross_Sales,float,Estimated sales before discount
12,Discount_Amount,float,Estimated monetary value of the discount
13,Sales_Per_Unit,float,Sales divided by quantity
14,Profit_Margin,float,Profit as a percentage of sales
15,Profit_Status,string,Shows whether the transaction generated profit...

In [48]:
#save data dictionary
data_dictionary.to_csv(
    "Superstore_Data_Dictionary.csv",
    index=False
)